//getelementsbytagname()
var a= document.getElementsByTagName('li')
console.log(a)
//getelementsbyclassname()
var b= document.getElementsByClassName('hero')
console.log(b)
//getElementbyid()
var c = document.getElementById('hero')
console.log(c)
//queryselector()
var d = document.querySelector('li')
console.log(d)
//queryselectorall()
var e = document.querySelectorAll('li')
console.log(e)